---
- hosts: 172.31.36.231
  become: yes
  vars: 
   var1: wget 
   var2: present 
   var3: yes 
  tasks:
  - name: installing wget using variables  
    apt:
     name: "{{var1}}"
     state: "{{var2}}"
     update_cache: "{{var3}}"